[package]
name = "tchess_classic"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
libtchess = { path = '../libtchess' }
rustc-hash = "2.1.1"
im-rc = "15.1.0"
